### ISSUE TITLE
Move JS front-end code to separate folder

### ISSUE THREAD

**Issue by Lewiscowles1986** [algb12/Commentia#10]
The JS code has nothing to do with the PHP system. The two should be separated either by repo, or by folders. `public` and `static` are both folder names that are common for front-end resources.

**Comment by algb12** [comment]
What do you mean by

> Front-end code

???
Pertaining to what file?

**Comment by algb12** [comment]
I will close this issue, as the JS front-end code is now in an `/assets` directory... The good side-effects of adhering to PSR-4, you're forced to separate front-end from back-end...
