### ISSUE TITLE
JS relies on constants. Perhaps consider two-stage process

### ISSUE THREAD

**Issue by Lewiscowles1986** [algb12/Commentia#11]
https://github.com/algb12/Commentia/blob/master/commentia.js#L1

It would be nice if users could alter the endpoint folder without editing your code

``` js
window.commentia.URL = window.commentia.URL || "api.php";
```

This will ensure that a sensible default is provided if one is not already available

**Comment by algb12** [comment]
Good enhancement solution, thanks! I need to intensively work on this project, as tomorrow's First Draft deadline in my company :/ My _top_ priority now is PSR-4...

**Comment by algb12** [comment]
Could you help me on how to exactly do this? If I replace `api.php` with your suggested line of code, I get an error. If I create the `window.commentia` object first, it works...\

But how would a potential user go along modifying the endpoint path? They would still need to edit api.php.

**Comment by Lewiscowles1986** [comment]
well it might still be `api.php`, changing that would require renaming the file or setting up rewrite rules for whatever web-server was being used. If for example I installed on `//mysite.com/commentia/api.php` and the js is in `mysite.com/commentia/assets/js/commentia.js`, then it won't be able to call the `api.php` just from `api.php`. Best-case it will use the root `/api.php` requiring someone to modify the structure of the program and includes or contaminate their app. Worst case (because you don't have leading `/`) it will require `api.php` for every post url or require a rewrite rule

I'll make a PR later today (probably early evening UK time)

**Comment by algb12** [comment]
Once again, thank you for your effort, our company (which I was asked not to disclose) sends best regards to you!!!
