### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by severak** [algb12/Commentia#4]
It needs some documentation to be usable.

**Comment by algb12** [comment]
I have a MD file ready to push to the repo... Just needs some minor edits - You mean a developer or user documentation???

**Comment by severak** [comment]
How to install and use on web.

**Comment by algb12** [comment]
I am very slow-going when it comes to the docs, as I made this for my boss, who would have prior knowledge about the code... But I'll push the README.md anyways, as it's good style to have a documentation for other developers and users (e.g. others in my company _besides_ the boss)...
